config/routes.rb
Futureproject::Application.routes.draw do
  get "static_pages/home"

  get "static_pages/help"

  resources :industries

  resources :feeds

  resources :challenges

end

app/models/challenge.rb
class Challenge < ActiveRecord::Base
  attr_accessible :feedid, :image, :impact, :industry, :link, :long, :score, :short

end

app/models/feed.rb
class Feed < ActiveRecord::Base
  attr_accessible :lastChecked, :link, :rating

  belongs_to :industry
end

app/models/industry.rb
class Industry < ActiveRecord::Base
  attr_accessible :name

  has_many :feed
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/challenges_controller.rb
class ChallengesController < ApplicationController
  # GET /challenges
  # GET /challenges.json
  def index
    @challenges = Challenge.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @challenges }
    end
  end

  # GET /challenges/1
  # GET /challenges/1.json
  def show
    @challenge = Challenge.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @challenge }
    end
  end

  # GET /challenges/new
  # GET /challenges/new.json
  def new
    @challenge = Challenge.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @challenge }
    end
  end

  # GET /challenges/1/edit
  def edit
    @challenge = Challenge.find(params[:id])
  end

  # POST /challenges
  # POST /challenges.json
  def create
    @challenge = Challenge.new(params[:challenge])

    respond_to do |format|
      if @challenge.save
        format.html { redirect_to @challenge, notice: 'Challenge was successfully created.' }
        format.json { render json: @challenge, status: :created, location: @challenge }
      else
        format.html { render action: "new" }
        format.json { render json: @challenge.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /challenges/1
  # PUT /challenges/1.json
  def update
    @challenge = Challenge.find(params[:id])

    respond_to do |format|
      if @challenge.update_attributes(params[:challenge])
        format.html { redirect_to @challenge, notice: 'Challenge was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @challenge.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /challenges/1
  # DELETE /challenges/1.json
  def destroy
    @challenge = Challenge.find(params[:id])
    @challenge.destroy

    respond_to do |format|
      format.html { redirect_to challenges_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  # GET /feeds
  # GET /feeds.json
  def index
    @feeds = Feed.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @feeds }
    end
  end

  # GET /feeds/1
  # GET /feeds/1.json
  def show
    @feed = Feed.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @feed }
    end
  end

  # GET /feeds/new
  # GET /feeds/new.json
  def new
    @feed = Feed.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @feed }
    end
  end

  # GET /feeds/1/edit
  def edit
    @feed = Feed.find(params[:id])
  end

  # POST /feeds
  # POST /feeds.json
  def create
    @feed = Feed.new(params[:feed])

    respond_to do |format|
      if @feed.save
        format.html { redirect_to @feed, notice: 'Feed was successfully created.' }
        format.json { render json: @feed, status: :created, location: @feed }
      else
        format.html { render action: "new" }
        format.json { render json: @feed.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /feeds/1
  # PUT /feeds/1.json
  def update
    @feed = Feed.find(params[:id])

    respond_to do |format|
      if @feed.update_attributes(params[:feed])
        format.html { redirect_to @feed, notice: 'Feed was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @feed.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /feeds/1
  # DELETE /feeds/1.json
  def destroy
    @feed = Feed.find(params[:id])
    @feed.destroy

    respond_to do |format|
      format.html { redirect_to feeds_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/industries_controller.rb
class IndustriesController < ApplicationController
  # GET /industries
  # GET /industries.json
  def index
    @industries = Industry.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @industries }
    end
  end

  # GET /industries/1
  # GET /industries/1.json
  def show
    @industry = Industry.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @industry }
    end
  end

  # GET /industries/new
  # GET /industries/new.json
  def new
    @industry = Industry.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @industry }
    end
  end

  # GET /industries/1/edit
  def edit
    @industry = Industry.find(params[:id])
  end

  # POST /industries
  # POST /industries.json
  def create
    @industry = Industry.new(params[:industry])

    respond_to do |format|
      if @industry.save
        format.html { redirect_to @industry, notice: 'Industry was successfully created.' }
        format.json { render json: @industry, status: :created, location: @industry }
      else
        format.html { render action: "new" }
        format.json { render json: @industry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /industries/1
  # PUT /industries/1.json
  def update
    @industry = Industry.find(params[:id])

    respond_to do |format|
      if @industry.update_attributes(params[:industry])
        format.html { redirect_to @industry, notice: 'Industry was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @industry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /industries/1
  # DELETE /industries/1.json
  def destroy
    @industry = Industry.find(params[:id])
    @industry.destroy

    respond_to do |format|
      format.html { redirect_to industries_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

# returns the full title on a per page basis

def full_title(page_title)
	base_title ="Rails tutorial"
	if page_title.empty?
		base_title
	else
		"#{base_title} | #{page_title}"
	end
end
end

app/helpers/challenges_helper.rb
module ChallengesHelper
end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/helpers/industries_helper.rb
module IndustriesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/challenges/_form.html.erb
<%= form_for(@challenge) do |f| %>
  <% if @challenge.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@challenge.errors.count, "error") %> prohibited this challenge from being saved:</h2>

      <ul>
      <% @challenge.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :short %><br />
    <%= f.text_field :short %>
  </div>
  <div class="field">
    <%= f.label :long %><br />
    <%= f.text_field :long %>
  </div>
  <div class="field">
    <%= f.label :link %><br />
    <%= f.text_field :link %>
  </div>
  <div class="field">
    <%= f.label :image %><br />
    <%= f.text_field :image %>
  </div>
  <div class="field">
    <%= f.label :industry %><br />
    <%= f.number_field :industry %>
  </div>
  <div class="field">
    <%= f.label :score %><br />
    <%= f.number_field :score %>
  </div>
  <div class="field">
    <%= f.label :impact %><br />
    <%= f.number_field :impact %>
  </div>
  <div class="field">
    <%= f.label :feedid %><br />
    <%= f.number_field :feedid %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/challenges/edit.html.erb
<h1>Editing challenge</h1>

<%= render 'form' %>

<%= link_to 'Show', @challenge %> |
<%= link_to 'Back', challenges_path %>

app/views/challenges/index.html.erb
<h1>Listing challenges</h1>

<table>
  <tr>
    <th>Short</th>
    <th>Long</th>
    <th>Link</th>
    <th>Image</th>
    <th>Industry</th>
    <th>Score</th>
    <th>Impact</th>
    <th>Feedid</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @challenges.each do |challenge| %>
  <tr>
    <td><%= challenge.short %></td>
    <td><%= challenge.long %></td>
    <td><%= challenge.link %></td>
    <td><%= challenge.image %></td>
    <td><%= challenge.industry %></td>
    <td><%= challenge.score %></td>
    <td><%= challenge.impact %></td>
    <td><%= challenge.feedid %></td>
    <td><%= link_to 'Show', challenge %></td>
    <td><%= link_to 'Edit', edit_challenge_path(challenge) %></td>
    <td><%= link_to 'Destroy', challenge, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Challenge', new_challenge_path %>

app/views/challenges/new.html.erb
<h1>New challenge</h1>

<%= render 'form' %>

<%= link_to 'Back', challenges_path %>

app/views/challenges/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Short:</b>
  <%= @challenge.short %>
</p>

<p>
  <b>Long:</b>
  <%= @challenge.long %>
</p>

<p>
  <b>Link:</b>
  <%= @challenge.link %>
</p>

<p>
  <b>Image:</b>
  <%= @challenge.image %>
</p>

<p>
  <b>Industry:</b>
  <%= @challenge.industry %>
</p>

<p>
  <b>Score:</b>
  <%= @challenge.score %>
</p>

<p>
  <b>Impact:</b>
  <%= @challenge.impact %>
</p>

<p>
  <b>Feedid:</b>
  <%= @challenge.feedid %>
</p>


<%= link_to 'Edit', edit_challenge_path(@challenge) %> |
<%= link_to 'Back', challenges_path %>

app/views/feeds/_form.html.erb
<%= form_for(@feed) do |f| %>
  <% if @feed.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@feed.errors.count, "error") %> prohibited this feed from being saved:</h2>

      <ul>
      <% @feed.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :link %><br />
    <%= f.text_field :link %>
  </div>
  <div class="field">
    <%= f.label :lastChecked %><br />
    <%= f.date_select :lastChecked %>
  </div>
  <div class="field">
    <%= f.label :rating %><br />
    <%= f.number_field :rating %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/feeds/edit.html.erb
<h1>Editing feed</h1>

<%= render 'form' %>

<%= link_to 'Show', @feed %> |
<%= link_to 'Back', feeds_path %>

app/views/feeds/index.html.erb
<h1>Listing feeds</h1>

<table>
  <tr>
    <th>Link</th>
    <th>Lastchecked</th>
    <th>Rating</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @feeds.each do |feed| %>
  <tr>
    <td><%= feed.link %></td>
    <td><%= feed.lastChecked %></td>
    <td><%= feed.rating %></td>
    <td><%= link_to 'Show', feed %></td>
    <td><%= link_to 'Edit', edit_feed_path(feed) %></td>
    <td><%= link_to 'Destroy', feed, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Feed', new_feed_path %>

app/views/feeds/new.html.erb
<h1>New feed</h1>

<%= render 'form' %>

<%= link_to 'Back', feeds_path %>

app/views/feeds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Link:</b>
  <%= @feed.link %>
</p>

<p>
  <b>Lastchecked:</b>
  <%= @feed.lastChecked %>
</p>

<p>
  <b>Rating:</b>
  <%= @feed.rating %>
</p>


<%= link_to 'Edit', edit_feed_path(@feed) %> |
<%= link_to 'Back', feeds_path %>

app/views/industries/_form.html.erb
<%= form_for(@industry) do |f| %>
  <% if @industry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@industry.errors.count, "error") %> prohibited this industry from being saved:</h2>

      <ul>
      <% @industry.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/industries/edit.html.erb
<h1>Editing industry</h1>

<%= render 'form' %>

<%= link_to 'Show', @industry %> |
<%= link_to 'Back', industries_path %>

app/views/industries/index.html.erb
<h1>Listing industries</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @industries.each do |industry| %>
  <tr>
    <td><%= industry.name %></td>
    <td><%= link_to 'Show', industry %></td>
    <td><%= link_to 'Edit', edit_industry_path(industry) %></td>
    <td><%= link_to 'Destroy', industry, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Industry', new_industry_path %>

app/views/industries/new.html.erb
<h1>New industry</h1>

<%= render 'form' %>

<%= link_to 'Back', industries_path %>

app/views/industries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @industry.name %>
</p>


<%= link_to 'Edit', edit_industry_path(@industry) %> |
<%= link_to 'Back', industries_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
  	<meta charset="utf-8" />

  	<!-- Uncomment to make IE8 render like IE7 -->
  	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

  	<!-- Set the viewport width to device width for mobile -->
  	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

  	<title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

  	<%= stylesheet_link_tag    "application" %>
  	<%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= csrf_meta_tags %>

    
  </head>

  <body>

    <div class="fixed">
<nav class="top-bar">

  <ul class="title-area">
    <!-- Title Area -->
    <li class="name">
      <h1><a href="#">realent</a></h1>
    </li>
    <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
    <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
  </ul>


  <section class="top-bar-section">

    <!-- Right Nav Section -->
    <ul class="right">
      <li class="divider hide-for-small"></li>
      <li><a href="#">About</a></li>
      <li><a href="#">Contact</a></li>
    </ul>
  </section>
</nav>
</div>

  <header>
    <div class="row">
      <div class="twelve columns">
        <h1>Challenge feed</h1>
        <h4>Forget photo apps, be a man, solve real problems.</h4>
      </div>
    </div>
  </header>

 
  <header class="gray">
    <div class="row">
      <div class="twelve columns">
        <h6>Perhaps you could solve the <a href="#">bandwidth challenge </a> or improve <a href="#">medication adherence</a>...</h6>
      </div>
    </div>
  </header>


<section id="mainContent">
  <div class="row">


    <div class="large-2 columns push-ten">

          <ul class="side-nav">
          <li class="active"><a href="index.html">&larr; Home</a></li>
          <li class="divider"></li>
          <li onclick="adminMode()"><a>Admin Mode</a></li>
          <li onclick="topQuotes()"><a>Top Challenges</a></li>
          <li onclick="justSpottedQuotes()"><a>Just spotted</a></li>
          <br>
          <li class="divider"></li>
          <li><p>Verticals</p></li>
          <li><a href="#">Telecoms</a></li>
          <li><a href="#">Retail</a></li>
          <li><a href="#">Media</a></li>
          <li><a href="#">Healthcare</a></li>
          <li><a href="#">Consumer</a></li>

        </ul>

    </div>

    <div class="large-10 columns push-two">


      <div class="row" id="descriptionpanel">


          <div class="large-7 columns" id="introduction">

            <h1><%= yield(:title) %></h1>

            <p class="show-for-small"><a href="index.php">&larr; Back to Home</a></p>
            <h2>A hidden goldmine</h2>
            <h4 class="subheader">How to get started</h4>

            <p>If you want to escape the corperate grind and start a company ideas can be hard to find, it feels like everything has been done and it's impossible to predict which fad app will be the next big thing. The key ingredient to real entrepreneurship is solving a pressing problem, here we cut out the serindipity and highlight hundreds of opportunties across a range of industries as they're mentioned.

            <!--  -->
          </div>



        <div class="large-4 large-offset-1 columns" id="advertblock">
          
          <div class="row">
            <br> 
          
            <h5>Get the weekly idea update</h5>

            <form>
      <div class="row collapse">
        <div class="small-9 columns">
          <input type="text" placeholder="Enter email">
        </div>
        <div class="small-3 columns">
          <a href="#" class="button prefix">Go!</a>
        </div>
      </div>
            </form>
           
          </div>


         </div>


        <div class="large-12 columns">

         <!--  repeating grid. The columsn are filled in dynamically using
         the template at the bottom--> 

        <ul class="small-block-grid-2 large-block-grid-4">

        <li>
          <div class="line1" id="line1"></div><!-- column1 -->


            <div class="opboxclear">
            <!-- <img src="images/radio.jpg" alt=""> -->
             <h4>Title</h4><p> <a href="#" data-reveal-id="myModal" data-animationspeed="300" data-animation="pop">Full info</a></p>
             <p>A summary will go here</p>

             <div class="controlpannel">

            <i class="foundicon-up-arrow" onclick='updateQuote("{{objectId}}",2)')></i> 
            <i class="foundicon-down-arrow" onclick='updateQuote("{{objectId}}",3)'></i>
            <i class="foundicon-remove" onclick='updateQuote("{{objectId}}",1)'></i> 
             </div>

            </div>
           <div class=opboxspacer></div> 


        </li>
        <li>
          <div class="line1" id="line2"></div><!-- column1 -->
        </li>
        <li>
          <div class="line1" id="line3"></div><!-- column1 -->
        </li>
        <li>
          <div class="line1" id="line4"></div><!-- column1 -->
        </li>
        </ul>
          
      </div> <!--  repeating grid --> 

    </div>

    </div>
  </div>
</section>




<!-- MORE INFO WINDOW -->


<div id="myModal" class="reveal-modal">
   <h1>Modal Title</h1>
   <p>Any content could go in here.</p>
   <a class="close-reveal-modal">&#215;</a>
</div>


    <%= yield %>

    
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<% provide(:title, 'Home') %>


<p>Find me in app/views/static_pages/home.html.erb</p>